"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ServerRoutes_1 = require("../../../admin/src/constants/ServerRoutes");
var express = require("express");
var router = express.Router();
var userStatisticsRouter = require('./UsersStatistics');
router.use(ServerRoutes_1.EntryPoint.USERS_STATISTICS, userStatisticsRouter);
var cookbooksStatisticsRouter = require('./CookBooksStatistics');
router.use(ServerRoutes_1.EntryPoint.COOKBOOKS_STATISTICS, cookbooksStatisticsRouter);
var recipesStatisticsRouter = require('./RecipesStatistics');
router.use(ServerRoutes_1.EntryPoint.RECIPES_STATISTICS, recipesStatisticsRouter);
var globalStatisticRouter = require('./GlobalStatistics');
router.use(ServerRoutes_1.EntryPoint.GLOBAL_STATISTICS, globalStatisticRouter);
module.exports = router;
